//
// Generated by JTB 1.2.2
//

package com.edb.gridsql.parser.core.visitor;
import com.edb.gridsql.parser.core.syntaxtree.*;
import java.util.*;

/**
 * All Object visitors must implement this interface.
 */
public interface ObjectVisitor {
   //
   // Object Auto class visitors
   //
   public Object visit(NodeList n, Object argu);
   public Object visit(NodeListOptional n, Object argu);
   public Object visit(NodeOptional n, Object argu);
   public Object visit(NodeSequence n, Object argu);
   public Object visit(NodeToken n, Object argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> FloatingPointNumber(prn)
    */
   public Object visit(numberValue n, Object argu);

   /**
    * f0 -> <STRING_LITERAL>
    */
   public Object visit(stringLiteral n, Object argu);

   /**
    * f0 -> <POSITION_>
    *       | <DATE_>
    *       | <DAY_>
    *       | <QUARTER_>
    *       | <TIME_>
    *       | <TIMESTAMP_>
    *       | <WITH_TIMEZONE_>
    *       | <WITHOUT_TIMEZONE_>
    *       | <DATETIME_>
    *       | <SAMLLDATETIME_>
    *       | <PASSWORD_>
    *       | <AVERAGE_>
    *       | <SQRT_>
    *       | <COUNT_>
    *       | <EXTRACT_>
    *       | <MAX_>
    *       | <CURRENTDATE_>
    *       | <CURRENT_TIME_>
    *       | <CURRENT_TIMESTAMP_>
    *       | <TRUNC_>
    *       | <TRUNCATE_>
    *       | <USER_>
    *       | <YEAR_>
    *       | <LENGTH_>
    *       | <LOWER_>
    *       | <MONTH_>
    *       | <HOUR_>
    *       | <MINUTE_>
    *       | <SECOND_>
    *       | <SUBSTRING_>
    *       | <NOW_>
    *       | <ADDDATE_>
    *       | <ADDTIME_>
    *       | <DAYNAME_>
    *       | <SUBDATE_>
    *       | <SUBTIME_>
    *       | <DATEDIFF_>
    *       | <MONTHNAME_>
    *       | <DAYOFWEEK_>
    *       | <DAYOFYEAR_>
    *       | <DAYOFMONTH_>
    *       | <WEEKOFYEAR_>
    *       | <WEEK_>
    *       | <ABS_>
    *       | <CEIL_>
    *       | <CEILING_>
    *       | <EXP_>
    *       | <FLOOR_>
    *       | <LN_>
    *       | <LOG_>
    *       | <LOG10_>
    *       | <PI_>
    *       | <POWER_>
    *       | <ROUND_>
    *       | <SIGN_>
    *       | <ASIN_>
    *       | <ATAN_>
    *       | <ATAN2_>
    *       | <ATN2_>
    *       | <COS_>
    *       | <ACOS_>
    *       | <COSH_>
    *       | <COT_>
    *       | <DEGREE_>
    *       | <RADIANS_>
    *       | <SIN_>
    *       | <TAN_>
    *       | <DATABASE_>
    *       | <VALUE_>
    *       | <VERSION_>
    *       | <MIN_>
    *       | <STDDEV_>
    *       | <STDDEV_POP_>
    *       | <STDDEV_SAMP_>
    *       | <SUM_>
    *       | <VARIANCE_>
    *       | <VARIANCE_POP_>
    *       | <VARIANCE_SAMP_> <ASCII_>
    *       | <LPAD_>
    *       | <RPAD_>
    *       | <LTRIM_>
    *       | <REPLACE_>
    *       | <RTRIM_>
    *       | <SUBSTR_>
    *       | <TRIM_>
    *       | <UPPER_>
    *       | <FIXED_>
    *       | <GREATEST_>
    *       | <LEAST_>
    *       | <INSTR_>
    *       | <SOUNDEX_>
    *       | <INITCAP_>
    *       | <LFILL_>
    *       | <MAPCHAR_>
    *       | <NUM_>
    *       | <CONCAT_WORD>
    *       | <CURTIME_>
    *       | <CURDATE_>
    *       | <TIMEOFDAY_>
    *       | <ISFINITE_>
    *       | <DATETRUNC_>
    *       | <DATEPART_>
    *       | <AGE_>
    *       | <LOCALTIME_>
    *       | <LOCALTIMESTAMP_>
    *       | <BIT_LENGTH_>
    *       | <CHAR_LENGTH_>
    *       | <CHARACTER_LENGTH_>
    *       | <CONVERT_>
    *       | <OCTET_LENGTH_>
    *       | <OVERLAY_>
    *       | <PLACING_>
    *       | <STORAGE_>
    *       | <TYPE_>
    *       | <BTRIM_>
    *       | <CHR_>
    *       | <DECODE_>
    *       | <ENCODE_>
    *       | <MD5_>
    *       | <PG_CLIENT_ENCODING_>
    *       | <QUOTE_IDENT_>
    *       | <QUOTE_LITERAL_>
    *       | <REPEAT_>
    *       | <SPLIT_PART_>
    *       | <STRPOS_>
    *       | <TO_ASCII_>
    *       | <TO_HEX_>
    *       | <TRANSLATE_>
    *       | <WIDTH_BUCKET_>
    *       | <SETSEED_>
    *       | <RANDOM_>
    *       | <CBRT_>
    *       | <GET_BIT_>
    *       | <GET_BYTE_>
    *       | <TO_DATE_>
    *       | <NVL_>
    *       | <NVL2_>
    *       | <CLOCK_TIMESTAMP_>
    *       | <STATEMENT_TIMESTAMP_>
    *       | <TRANSACTION_TIMESTAMP_>
    *       | <SMALLINT_>
    *       | <TINYINT_>
    *       | <INT2_>
    *       | <BYTEA_>
    *       | <BIGINT_>
    *       | <INT8_>
    *       | <BIGINTEGER_>
    *       | <INT_>
    *       | <INTEGER_>
    *       | <INT4_>
    *       | <REAL_>
    *       | <SMALLFLOAT_>
    *       | <FLOAT_>
    *       | <FLOAT4_>
    *       | <FLOAT8_>
    *       | <DECIMAL_>
    *       | <NUMERIC_>
    *       | <SMALLMONEY_>
    *       | <MONEY_>
    *       | <NUMBER_>
    *       | <CHAR_>
    *       | <CHARACHTER_>
    *       | <VARCHAR_>
    *       | <TINYTEXT_>
    *       | <VARCHAR2_>
    *       | <DATE_>
    *       | <TIME_>
    *       | <TIMESTAMP_>
    *       | <DEC_>
    *       | <DOUBLE_PRECISION_>
    *       | <NCHAR_>
    *       | <NATIONAL_>
    *       | <VARYING_>
    *       | <BOOLEAN_>
    *       | <INTERVAL_>
    *       | <TEXT_>
    *       | <MEDIUMTEXT_>
    *       | <LVARCHAR_>
    *       | <LONGTEXT_>
    *       | <LONG_VARCHAR_>
    *       | <LONG_>
    *       | <CLOB_>
    *       | <BLOB_>
    *       | <BINARY_>
    *       | <VARBINARY_>
    *       | <RAW_>
    *       | <LONG_RAW_>
    *       | <IMAGE_>
    *       | <BYTE_>
    *       | <CLUSTER_>
    *       | <CURRENT_USER_>
    *       | <NULLIF_>
    *       | <SET_BIT_>
    *       | <SET_BYTE_>
    *       | <TO_CHAR_>
    *       | <TO_NUMBER_>
    *       | <TO_TIMESTAMP_>
    *       | <ADD_MONTHS_>
    *       | <JUSTIFY_DAYS_>
    *       | <JUSTIFY_HOURS_>
    *       | <JUSTIFY_INTERVAL_>
    *       | <LAST_DAY_>
    *       | <MONTHS_BETWEEN_>
    *       | <NEXT_DAY_>
    *       | <CURRENT_DATABASE_>
    *       | <CURRENT_SCHEMA_>
    *       | <SYSDATE_>
    *       | <BIT_AND_>
    *       | <BIT_OR_>
    *       | <BOOL_AND_>
    *       | <BOOL_OR_>
    *       | <EVERY_>
    *       | <CORR_>
    *       | <COVAR_POP_>
    *       | <COVAR_SAMP_>
    *       | <REGR_AVGX_>
    *       | <REGR_AVGY_>
    *       | <REGR_COUNT_>
    *       | <REGR_INTERCEPT_>
    *       | <REGR_R2_>
    *       | <REGR_SLOPE_>
    *       | <REGR_SXX_>
    *       | <REGR_SXY_>
    *       | <REGR_SYY_>
    *       | <REGEXP_REPLACE_>
    *       | <ABBREV_>
    *       | <BROADCAST_>
    *       | <FAMILY_>
    *       | <HOST_>
    *       | <HOSTMASK_>
    *       | <MASKLEN_>
    *       | <NETMASK_>
    *       | <NETWORK_>
    *       | <SET_MASKLEN_>
    */
   public Object visit(UnreservedWords n, Object argu);

   /**
    * f0 -> <IDENTIFIER>
    *       | <QUOTED_IDENTIFIER>
    *       | UnreservedWords(prn)
    */
   public Object visit(Identifier n, Object argu);

   /**
    * f0 -> ( VacuumDatabase(prn) [ <SEMICOLON_> ] | AnalyzeDatabase(prn) [ <SEMICOLON_> ] | createTable(prn) [ <SEMICOLON_> ] | CreateTablespace(prn) [ <SEMICOLON_> ] | createIndex(prn) [ <SEMICOLON_> ] | dropTable(prn) [ <SEMICOLON_> ] | DropTablespace(prn) [ <SEMICOLON_> ] | SelectWithParenthesis(prn) [ <SEMICOLON_> ] | InsertTable(prn) [ <SEMICOLON_> ] | UpdateTable(prn) [ <SEMICOLON_> ] | Delete(prn) [ <SEMICOLON_> ] | Alter(prn) [ <SEMICOLON_> ] | DropIndex(prn) [ <SEMICOLON_> ] | RenameTable(prn) [ <SEMICOLON_> ] | UpdateStats(prn) [ <SEMICOLON_> ] | ShowAgents() [ <SEMICOLON_> ] | ShowDatabases() [ <SEMICOLON_> ] | ShowStatements() [ <SEMICOLON_> ] | ShowTables() [ <SEMICOLON_> ] | ShowTranIsolation() [ <SEMICOLON_> ] | BeginTransaction() [ <SEMICOLON_> ] | CommitTransaction() [ <SEMICOLON_> ] | RollbackTransaction() [ <SEMICOLON_> ] | DescribeTable(prn) [ <SEMICOLON_> ] | ShowConstraints(prn) [ <SEMICOLON_> ] | ShowIndexes(prn) [ <SEMICOLON_> ] | Deallocate(prn) [ <SEMICOLON_> ] | CreateUser(prn) [ <SEMICOLON_> ] | DropUser(prn) [ <SEMICOLON_> ] | AlterUser(prn) [ <SEMICOLON_> ] | Grant(prn) [ <SEMICOLON_> ] | Revoke(prn) [ <SEMICOLON_> ] | createView(prn) [ <SEMICOLON_> ] | DropView(prn) [ <SEMICOLON_> ] | ShowUsers(prn) [ <SEMICOLON_> ] | ShowViews(prn) [ <SEMICOLON_> ] | Cluster(prn) [ <SEMICOLON_> ] | Truncate(prn) [ <SEMICOLON_> ] | ExecDirect(prn) [ <SEMICOLON_> ] | Explain(prn) [ <SEMICOLON_> ] | SetProperty(prn) [ <SEMICOLON_> ] | ShowProperty(prn) [ <SEMICOLON_> ] | AddNodeToDB(prn) [ <SEMICOLON_> ] | DropNodeFromDB(prn) [ <SEMICOLON_> ] | StartDatabase(prn) [ <SEMICOLON_> ] | StopDatabase(prn) [ <SEMICOLON_> ] | ShutdownXDB(prn) [ <SEMICOLON_> ] | CreateDatabase(prn) [ <SEMICOLON_> ] | DropDatabase(prn) [ <SEMICOLON_> ] | CopyData(prn) [ <SEMICOLON_> ] | Kill(prn) [ <SEMICOLON_> ] | Unlisten(prn) [ <SEMICOLON_> ] )
    * f1 -> <EOF>
    */
   public Object visit(process n, Object argu);

   /**
    * f0 -> <COPY_>
    * f1 -> ( TableName(prn) [ ColumnNameListWithParenthesis(prn) ] | <PARENTHESIS_START_> Select(prn) <PARENTHESIS_CLOSE_> )
    * f2 -> ( <FROM_> ( <STDIN_> | <STRING_LITERAL> ) | <TO_> ( <STDOUT_> | <STRING_LITERAL> ) )
    * f3 -> [ [ <WITH_> ] ( FormatDefOIDS(prn) | FormatDefDelimiter(prn) | FormatDefNull(prn) | FormatDefCSV(prn) )+ ]
    */
   public Object visit(CopyData n, Object argu);

   /**
    * f0 -> <OIDS_>
    */
   public Object visit(FormatDefOIDS n, Object argu);

   /**
    * f0 -> <DELIMITER_>
    * f1 -> [ <AS_> ]
    * f2 -> <STRING_LITERAL>
    */
   public Object visit(FormatDefDelimiter n, Object argu);

   /**
    * f0 -> <NULL_>
    * f1 -> [ <AS_> ]
    * f2 -> <STRING_LITERAL>
    */
   public Object visit(FormatDefNull n, Object argu);

   /**
    * f0 -> <CSV_>
    * f1 -> ( <QUOTE_STRING_> [ <AS_> ] <STRING_LITERAL> | <ESCAPE_> [ <AS_> ] <STRING_LITERAL> | <FORCE_QUOTE_> ColumnNameList(prn) | <FORCE_NOT_NULL_> ColumnNameList(prn) )*
    */
   public Object visit(FormatDefCSV n, Object argu);

   /**
    * f0 -> <ADD_NODE_>
    * f1 -> <INT_LITERAL>
    * f2 -> ( "," <INT_LITERAL> )*
    * f3 -> [ <MANUAL_> ]
    */
   public Object visit(AddNodeToDB n, Object argu);

   /**
    * f0 -> <DROP_NODE_>
    * f1 -> <INT_LITERAL>
    * f2 -> ( "," <INT_LITERAL> )*
    * f3 -> [ <FORCE_> ]
    */
   public Object visit(DropNodeFromDB n, Object argu);

   /**
    * f0 -> <START_DB_>
    * f1 -> Identifier(prn)
    * f2 -> ( "," Identifier(prn) )*
    * f3 -> [ <WAIT_TIMEOUT_> <INT_LITERAL> ]
    */
   public Object visit(StartDatabase n, Object argu);

   /**
    * f0 -> <STOP_DB_>
    * f1 -> Identifier(prn)
    * f2 -> ( "," Identifier(prn) )*
    */
   public Object visit(StopDatabase n, Object argu);

   /**
    * f0 -> <SHUT_DOWN_>
    * f1 -> [ <FORCE_> ]
    */
   public Object visit(ShutdownXDB n, Object argu);

   /**
    * f0 -> <CREATE_DB_>
    * f1 -> Identifier(prn)
    * f2 -> [ [ <WITH_> ] <OWNER_> [ "=" ] Identifier(prn) ]
    * f3 -> [ <MANUAL_> ]
    * f4 -> <ON_>
    * f5 -> ( <NODE_> | <NODES_> )
    * f6 -> <INT_LITERAL>
    * f7 -> ( "," <INT_LITERAL> )*
    */
   public Object visit(CreateDatabase n, Object argu);

   /**
    * f0 -> <DROP_DB_>
    * f1 -> Identifier(prn)
    * f2 -> [ <FORCE_> ]
    */
   public Object visit(DropDatabase n, Object argu);

   /**
    * f0 -> <EXEC_>
    * f1 -> <DIRECT_>
    * f2 -> <ON_>
    * f3 -> ( <ALL_> | ( <NODE_> | <NODES_> ) <INT_LITERAL> ( "," <INT_LITERAL> )* )
    * f4 -> <STRING_LITERAL>
    */
   public Object visit(ExecDirect n, Object argu);

   /**
    * f0 -> <EXPLAIN_>
    * f1 -> [ <VERBOSE_> ]
    * f2 -> Select(prn)
    */
   public Object visit(Explain n, Object argu);

   /**
    * f0 -> <VACUUM_>
    * f1 -> [ <FULL_> | <FREEZE_> ]
    * f2 -> [ TableName(prn) | AnalyzeDatabase(prn) ]
    */
   public Object visit(VacuumDatabase n, Object argu);

   /**
    * f0 -> <ANALYZE_>
    * f1 -> [ TableName(prn) [ <PARENTHESIS_START_> ColumnNameList(prn) <PARENTHESIS_CLOSE_> ] ]
    */
   public Object visit(AnalyzeDatabase n, Object argu);

   /**
    * f0 -> <CREATE_>
    * f1 -> <TABLESPACE_>
    * f2 -> Identifier(prn)
    * f3 -> TablespaceLocation(prn)
    * f4 -> ( "," TablespaceLocation(prn) )*
    */
   public Object visit(CreateTablespace n, Object argu);

   /**
    * f0 -> <DROP_>
    * f1 -> <TABLESPACE_>
    * f2 -> Identifier(prn)
    */
   public Object visit(DropTablespace n, Object argu);

   /**
    * f0 -> <LOCATION_>
    * f1 -> stringLiteral(prn)
    * f2 -> <ON_>
    * f3 -> ( <ALL_> | ( <NODE_> | <NODES_> ) <INT_LITERAL> ( "," <INT_LITERAL> )* )
    */
   public Object visit(TablespaceLocation n, Object argu);

   /**
    * f0 -> <UPDATE_STAT_>
    * f1 -> ( <COLUMN_> ( <PARENTHESIS_START_> <STAR_> <PARENTHESIS_CLOSE_> | <PARENTHESIS_START_> ColumnNameList(prn) <PARENTHESIS_CLOSE_> ) <FOR_> TableName(prn) | TableName(prn) | <STAR_> )
    */
   public Object visit(UpdateStats n, Object argu);

   /**
    * f0 -> <RENAME_>
    * f1 -> <TABLE_>
    * f2 -> TableName(prn)
    * f3 -> <TO_>
    * f4 -> TableName(prn)
    */
   public Object visit(RenameTable n, Object argu);

   /**
    * f0 -> <DROP_>
    * f1 -> <INDEX_>
    * f2 -> Identifier(prn)
    * f3 -> [ <ON_> TableName(prn) ]
    */
   public Object visit(DropIndex n, Object argu);

   /**
    * f0 -> <ALTER_>
    * f1 -> ( AlterTable(prn) | AlterTableSpace(prn) )
    */
   public Object visit(Alter n, Object argu);

   /**
    * f0 -> <TABLESPACE_>
    * f1 -> Identifier(prn)
    * f2 -> <RENAME_>
    * f3 -> <TO_>
    * f4 -> Identifier(prn)
    */
   public Object visit(AlterTableSpace n, Object argu);

   /**
    * f0 -> <TABLE_>
    * f1 -> TableName(prn)
    * f2 -> AlterTableActon(prn)
    * f3 -> ( "," AlterTableActon(prn) )*
    */
   public Object visit(AlterTable n, Object argu);

   /**
    * f0 -> AddDef(prn)
    *       | DropDef(prn)
    *       | AlterDef(prn)
    *       | RenameDef(prn)
    *       | OwnerDef(prn)
    *       | SetTablespace(prn)
    *       | Inherit(prn)
    */
   public Object visit(AlterTableActon n, Object argu);

   /**
    * f0 -> [ <NO_> ]
    * f1 -> <INHERIT_>
    * f2 -> TableName(prn)
    */
   public Object visit(Inherit n, Object argu);

   /**
    * f0 -> <SET_>
    * f1 -> <TABLESPACE_>
    * f2 -> Identifier(prn)
    */
   public Object visit(SetTablespace n, Object argu);

   /**
    * f0 -> <SET_>
    * f1 -> ( Identifier(prn) [ <TO_> | "=" ] ( <STRING_LITERAL> | Identifier(prn) | <ON_> | <TRUE_> | <FALSE_> ) | <TRANSACTION_> <ISOLATION_LEVEL_> IsolationLevel(prn) )
    */
   public Object visit(SetProperty n, Object argu);

   /**
    * f0 -> ( <SERIALIZABLE_> | <REPEATABLE_READ_> | <READ_COMMITTED_> | <READ_UNCOMMITTED_> )
    */
   public Object visit(IsolationLevel n, Object argu);

   /**
    * f0 -> <SHOW_>
    * f1 -> ( <IDENTIFIER> | <ALL_> | <QUOTED_IDENTIFIER> )
    */
   public Object visit(ShowProperty n, Object argu);

   /**
    * f0 -> <OWNER_TO_>
    * f1 -> ( <PUBLIC_> | Identifier(prn) )
    */
   public Object visit(OwnerDef n, Object argu);

   /**
    * f0 -> <CONSTRAINT_>
    * f1 -> Identifier(prn)
    */
   public Object visit(Constraint n, Object argu);

   /**
    * f0 -> <ADD_>
    * f1 -> ( [ <COLUMN_> ] ColumnDeclare(prn) [ <FIRST_> | <AFTER_> Identifier(prn) ] | [ Constraint(prn) ] ( PrimaryKeyDef(prn) | ForeignKeyDef(prn) | CheckDef(prn) ) )
    */
   public Object visit(AddDef n, Object argu);

   /**
    * f0 -> <DROP_>
    * f1 -> ( [ <COLUMN_> ] Identifier(prn) | Constraint(prn) | <PRIMARYKEY_> )
    */
   public Object visit(DropDef n, Object argu);

   /**
    * f0 -> <RENAME_>
    * f1 -> [ <COLUMN_> ]
    * f2 -> Identifier(prn)
    * f3 -> <TO_>
    * f4 -> Identifier(prn)
    */
   public Object visit(RenameDef n, Object argu);

   /**
    * f0 -> ( <MODIFY_> | <ALTER_> )
    * f1 -> [ <COLUMN_> ]
    * f2 -> AlterDefOperation(prn)
    */
   public Object visit(AlterDef n, Object argu);

   /**
    * f0 -> Identifier(prn)
    * f1 -> ( AlterDefOperationType(prn) | AlterDefOperationSet(prn) | DropDefaultNotNull(prn) )
    */
   public Object visit(AlterDefOperation n, Object argu);

   /**
    * f0 -> <TYPE_>
    * f1 -> types()
    * f2 -> [ <USING_> ( <STRING_LITERAL> | <NULL_> | <DATE_> | <TIME_> | <TIMESTAMP_> | <INT_LITERAL> | <DECIMAL_LITERAL> | IntervalLiterals(prn) ) ]
    */
   public Object visit(AlterDefOperationType n, Object argu);

   /**
    * f0 -> <SET_>
    * f1 -> ( DefaultSpec(prn) | <NOT_> <NULL_> | <STATISTICS_> <INT_LITERAL> | <STORAGE_> )
    */
   public Object visit(AlterDefOperationSet n, Object argu);

   /**
    * f0 -> <DROP_>
    * f1 -> ( <DEFAULT_> | <NOT_> <NULL_> )
    */
   public Object visit(DropDefaultNotNull n, Object argu);

   /**
    * f0 -> <DELETE_>
    * f1 -> <FROM_>
    * f2 -> TableName(prn)
    * f3 -> [ WhereClause(prn) ]
    */
   public Object visit(Delete n, Object argu);

   /**
    * f0 -> <UPDATE_>
    * f1 -> TableName(prn)
    * f2 -> <SET_>
    * f3 -> SetUpdateClause(prn)
    * f4 -> ( "," SetUpdateClause(prn) )*
    * f5 -> [ WhereClause(prn) ]
    */
   public Object visit(UpdateTable n, Object argu);

   /**
    * f0 -> [ TableName(prn) "." ]
    * f1 -> Identifier(prn)
    * f2 -> "="
    * f3 -> SQLSimpleExpression(prn)
    */
   public Object visit(SetUpdateClause n, Object argu);

   /**
    * f0 -> <CREATE_>
    * f1 -> [ <UNIQUE_> ]
    * f2 -> <INDEX_>
    * f3 -> Identifier(prn)
    * f4 -> <ON_>
    * f5 -> TableName(prn)
    * f6 -> [ <USING_> Identifier(prn) ]
    * f7 -> <PARENTHESIS_START_>
    * f8 -> columnListIndexSpec(prn)
    * f9 -> <PARENTHESIS_CLOSE_>
    * f10 -> [ tablespaceDef(prn) ]
    * f11 -> [ WhereClause(prn) ]
    */
   public Object visit(createIndex n, Object argu);

   /**
    * f0 -> ( Identifier(prn) | <PARENTHESIS_START_> SQLSimpleExpression(prn) <PARENTHESIS_CLOSE_> )
    * f1 -> [ <ASC_> | <DESC_> | Identifier(prn) ]
    * f2 -> ( "," ( Identifier(prn) | <PARENTHESIS_START_> SQLSimpleExpression(prn) <PARENTHESIS_CLOSE_> ) [ <ASC_> | <DESC_> | Identifier(prn) ] )*
    */
   public Object visit(columnListIndexSpec n, Object argu);

   /**
    * f0 -> <CREATE_>
    * f1 -> [ [ <LOCAL_> | <GLOBAL_> ] ( <TEMP_> | <TEMPORARY_> ) ]
    * f2 -> <TABLE_>
    * f3 -> TableName(prn)
    * f4 -> ( <PARENTHESIS_START_> CreateDefinition(prn) ( "," CreateDefinition(prn) )* <PARENTHESIS_CLOSE_> [ PartitionDeclare(prn) ] [ inheritsDef(prn) ] [ WithXRowID(prn) ] [ OnCommitClause(prn) ] [ tablespaceDef(prn) ] | [ <PARENTHESIS_START_> ColumnNameList(prn) <PARENTHESIS_CLOSE_> ] [ PartitionDeclare(prn) ] [ WithXRowID(prn) ] [ OnCommitClause(prn) ] [ tablespaceDef(prn) ] <AS_> SelectWithoutOrderAndSet(prn) )
    */
   public Object visit(createTable n, Object argu);

   /**
    * f0 -> <ON_COMMIT_>
    * f1 -> ( <PRESERVE_ROWS_> | <DELETE_ROWS_> | <DROP_> )
    */
   public Object visit(OnCommitClause n, Object argu);

   /**
    * f0 -> <WITH_XROWID_>
    *       | <WITHOUT_XROWID_>
    */
   public Object visit(WithXRowID n, Object argu);

   /**
    * f0 -> <TABLESPACE_>
    * f1 -> Identifier(prn)
    */
   public Object visit(tablespaceDef n, Object argu);

   /**
    * f0 -> <INHERITS_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> TableName(prn)
    * f3 -> ( "," TableName(prn) )*
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(inheritsDef n, Object argu);

   /**
    * f0 -> ( <CREATE_> | <REPLACE_> )
    * f1 -> <VIEW_>
    * f2 -> TableName(prn)
    * f3 -> [ ColumnNameListWithParenthesis(prn) ]
    * f4 -> <AS_>
    * f5 -> SelectWithoutOrder(prn)
    */
   public Object visit(createView n, Object argu);

   /**
    * f0 -> <PARENTHESIS_START_>
    * f1 -> ColumnNameList(prn)
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(ColumnNameListWithParenthesis n, Object argu);

   /**
    * f0 -> <DROP_>
    * f1 -> <VIEW_>
    * f2 -> TableName(prn)
    */
   public Object visit(DropView n, Object argu);

   /**
    * f0 -> <DROP_>
    * f1 -> <TABLE_>
    * f2 -> TableName(prn)
    * f3 -> ( "," TableName(prn) )*
    */
   public Object visit(dropTable n, Object argu);

   /**
    * f0 -> <INSERT_>
    * f1 -> [ <INTO_> ]
    * f2 -> TableName(prn)
    * f3 -> [ <PARENTHESIS_START_> ColumnNameList(prn) <PARENTHESIS_CLOSE_> ]
    * f4 -> ( <VALUES_> <PARENTHESIS_START_> SQLExpressionList(prn) <PARENTHESIS_CLOSE_> | SelectWithoutOrderWithParenthesis(prn) )
    */
   public Object visit(InsertTable n, Object argu);

   /**
    * f0 -> <PRIMARYKEY_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> ColumnNameList(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(PrimaryKeyDef n, Object argu);

   /**
    * f0 -> <CHECK_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> skip_to_matching_brace(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(CheckDef n, Object argu);

   /**
    * f0 -> ColumnDeclare(prn)
    *       | [ Constraint(prn) ] ( PrimaryKeyDef(prn) | ForeignKeyDef(prn) | CheckDef(prn) )
    */
   public Object visit(CreateDefinition n, Object argu);

   /**
    * f0 -> Identifier(prn)
    * f1 -> types()
    * f2 -> [ <NOT_> <NULL_> | <NULL_> ]
    * f3 -> [ DefaultSpec(prn) ]
    * f4 -> [ <PRIMARYKEY_> ]
    * f5 -> [ <CHECK_> <PARENTHESIS_START_> SQLComplexExpression(prn) <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(ColumnDeclare n, Object argu);

   /**
    * f0 -> <FOREIGNKEY_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> ColumnNameList(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    * f4 -> <REFERENCES_>
    * f5 -> TableName(prn)
    * f6 -> <PARENTHESIS_START_>
    * f7 -> ColumnNameList(prn)
    * f8 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(ForeignKeyDef n, Object argu);

   /**
    * f0 -> <DEFAULT_>
    * f1 -> SQLSimpleExpression(prn)
    */
   public Object visit(DefaultSpec n, Object argu);

   /**
    * f0 -> <PARTITIONINGKEY_> [ Identifier(prn) ] <ON_> PartitionChoice(prn)
    *       | <PARTITION_WITH_> <PARENT_>
    *       | <REPLICATED_>
    *       | <ON_> ( <NODE_> | <NODES_> ) <INT_LITERAL>
    *       | <ROUND_ROBIN_> <ON_> PartitionChoice(prn)
    */
   public Object visit(PartitionDeclare n, Object argu);

   /**
    * f0 -> <ALL_>
    *       | ( <NODE_> | <NODES_> ) NodePartitionList(prn)
    */
   public Object visit(PartitionChoice n, Object argu);

   /**
    * f0 -> <INT_LITERAL>
    * f1 -> ( "," <INT_LITERAL> )+
    */
   public Object visit(NodePartitionList n, Object argu);

   /**
    * f0 -> IntegerDataType()
    *       | SmallIntDataType()
    *       | RealDataType()
    *       | DoublePrecision()
    *       | FloatDataType()
    *       | DecimalDataType()
    *       | NumericDataType()
    *       | FixedDataType()
    *       | CharachterDataType()
    *       | VarCharDataType()
    *       | DateDataType()
    *       | TimeDataType()
    *       | TimeStampDataType()
    *       | BooleanDataType()
    *       | NationalCharDataType()
    *       | SerialDataType()
    *       | BigSerialDataType()
    *       | BigIntDataType()
    *       | IntervalDataType()
    *       | TextDataType()
    *       | BLOBDataType()
    *       | BitDataType()
    *       | VarBitDataType()
    *       | MacAddrDataType()
    *       | CidrDataType()
    *       | InetDataType()
    */
   public Object visit(types n, Object argu);

   /**
    * f0 -> <YEAR_>
    *       | <QUARTER_>
    *       | <MONTH_>
    *       | <WEEK_>
    *       | <DAY_>
    *       | <HOUR_>
    *       | <MINUTE_>
    *       | <SECOND_>
    */
   public Object visit(DatetimeField n, Object argu);

   /**
    * f0 -> DatetimeField()
    * f1 -> <TO_>
    * f2 -> DatetimeField()
    */
   public Object visit(IntervalQualifier n, Object argu);

   /**
    * f0 -> <INTERVAL_>
    * f1 -> [ IntervalQualifier() ]
    */
   public Object visit(IntervalDataType n, Object argu);

   /**
    * f0 -> <TEXT_>
    *       | <CLOB_>
    *       | <LONG_>
    *       | <LONG_VARCHAR_>
    *       | <LONGTEXT_>
    *       | <LVARCHAR_>
    *       | <MEDIUMTEXT_>
    */
   public Object visit(TextDataType n, Object argu);

   /**
    * f0 -> <BLOB_>
    *       | <BYTEA_>
    *       | <BYTE_>
    *       | <BINARY_>
    *       | <IMAGE_>
    *       | <LONG_RAW_>
    *       | <RAW_>
    *       | <VARBINARY_>
    */
   public Object visit(BLOBDataType n, Object argu);

   /**
    * f0 -> <BIT_>
    * f1 -> [ LengthSpec() ]
    */
   public Object visit(BitDataType n, Object argu);

   /**
    * f0 -> <VARBIT_>
    * f1 -> [ LengthSpec() ]
    */
   public Object visit(VarBitDataType n, Object argu);

   /**
    * f0 -> <MACADDR_>
    */
   public Object visit(MacAddrDataType n, Object argu);

   /**
    * f0 -> <CIDR_>
    */
   public Object visit(CidrDataType n, Object argu);

   /**
    * f0 -> <INET_>
    */
   public Object visit(InetDataType n, Object argu);

   /**
    * f0 -> <BOOLEAN_>
    */
   public Object visit(BooleanDataType n, Object argu);

   /**
    * f0 -> ( <SMALLINT_> | <INT2_> ) [ <SERIAL_> ] UnsignedZeroFillSpecs()
    *       | <TINYINT_>
    */
   public Object visit(SmallIntDataType n, Object argu);

   /**
    * f0 -> ( <BIGINT_> | <BIGINTEGER_> | <INT8_> )
    * f1 -> [ <SERIAL_> ]
    * f2 -> UnsignedZeroFillSpecs()
    */
   public Object visit(BigIntDataType n, Object argu);

   /**
    * f0 -> <SERIAL_>
    */
   public Object visit(SerialDataType n, Object argu);

   /**
    * f0 -> <BIGSERIAL_>
    */
   public Object visit(BigSerialDataType n, Object argu);

   /**
    * f0 -> ( <REAL_> | <SMALLFLOAT_> | <FLOAT4_> )
    * f1 -> UnsignedZeroFillSpecs()
    */
   public Object visit(RealDataType n, Object argu);

   /**
    * f0 -> ( <INT_> | <INTEGER_> | <INT4_> )
    * f1 -> [ <SERIAL_> ]
    * f2 -> UnsignedZeroFillSpecs()
    */
   public Object visit(IntegerDataType n, Object argu);

   /**
    * f0 -> <FLOAT_>
    * f1 -> [ LengthSpec() ]
    * f2 -> UnsignedZeroFillSpecs()
    */
   public Object visit(FloatDataType n, Object argu);

   /**
    * f0 -> <TIMESTAMP_> [ LengthSpec() ] [ ( <WITH_TIMEZONE_> | <WITHOUT_TIMEZONE_> ) ]
    *       | <DATETIME_>
    *       | <SAMLLDATETIME_>
    */
   public Object visit(TimeStampDataType n, Object argu);

   /**
    * f0 -> <TIME_>
    * f1 -> [ LengthSpec() ]
    * f2 -> [ ( <WITH_TIMEZONE_> | <WITHOUT_TIMEZONE_> ) ]
    */
   public Object visit(TimeDataType n, Object argu);

   /**
    * f0 -> <DATE_>
    */
   public Object visit(DateDataType n, Object argu);

   /**
    * f0 -> ( <VARCHAR_> | <VARCHAR2_> ) [ LengthSpec() ]
    *       | <TINYTEXT_>
    */
   public Object visit(VarCharDataType n, Object argu);

   /**
    * f0 -> ( <NUMERIC_> | <NUMBER_> ) [ PrecisionSpec() ] UnsignedZeroFillSpecs()
    *       | <MONEY_>
    *       | <SMALLMONEY_>
    *       | <YEAR_>
    */
   public Object visit(NumericDataType n, Object argu);

   /**
    * f0 -> ( <DECIMAL_> | <DEC_> )
    * f1 -> [ PrecisionSpec() ]
    * f2 -> UnsignedZeroFillSpecs()
    */
   public Object visit(DecimalDataType n, Object argu);

   /**
    * f0 -> <FIXED_>
    * f1 -> PrecisionSpec()
    * f2 -> UnsignedZeroFillSpecs()
    */
   public Object visit(FixedDataType n, Object argu);

   /**
    * f0 -> ( <NCHAR_> | <NATIONAL_> ( <CHAR_> | <CHARACHTER_> ) )
    * f1 -> [ <VARYING_> ]
    * f2 -> [ LengthSpec() ]
    */
   public Object visit(NationalCharDataType n, Object argu);

   /**
    * f0 -> <DOUBLE_PRECISION_>
    *       | <FLOAT8_>
    */
   public Object visit(DoublePrecision n, Object argu);

   /**
    * f0 -> ( <CHARACHTER_> | <CHAR_> )
    * f1 -> [ <VARYING_> ]
    * f2 -> [ LengthSpec() ]
    */
   public Object visit(CharachterDataType n, Object argu);

   /**
    * f0 -> <PARENTHESIS_START_>
    * f1 -> <INT_LITERAL>
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(LengthSpec n, Object argu);

   /**
    * f0 -> [ <UNSIGNED_> ]
    * f1 -> [ <ZEROFILL_> ]
    */
   public Object visit(UnsignedZeroFillSpecs n, Object argu);

   /**
    * f0 -> <PARENTHESIS_START_>
    * f1 -> <INT_LITERAL>
    * f2 -> [ "," <INT_LITERAL> ]
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(PrecisionSpec n, Object argu);

   /**
    * f0 -> Select(prn)
    */
   public Object visit(SelectWithParenthesis n, Object argu);

   /**
    * f0 -> SelectWithoutOrderWithParenthesis(prn)
    * f1 -> [ OrderByClause(prn) ]
    * f2 -> [ LimitClause(prn) ]
    * f3 -> [ OffsetClause(prn) ]
    */
   public Object visit(Select n, Object argu);

   /**
    * f0 -> SelectWithoutOrder(prn)
    */
   public Object visit(SelectWithoutOrderWithParenthesis n, Object argu);

   /**
    * f0 -> SelectWithoutOrderAndSetWithParenthesis(prn)
    * f1 -> ( <UNION_> [ <ALL_> ] ( SelectWithoutOrderAndSet(prn) | UnionSpec(prn) ) )*
    */
   public Object visit(SelectWithoutOrder n, Object argu);

   /**
    * f0 -> SelectWithoutOrderAndSet(prn)
    *       | <PARENTHESIS_START_> SelectWithoutOrderAndSetWithParenthesis(prn) <PARENTHESIS_CLOSE_>
    */
   public Object visit(SelectWithoutOrderAndSetWithParenthesis n, Object argu);

   /**
    * f0 -> <PARENTHESIS_START_>
    * f1 -> SelectWithoutOrder(prn)
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(UnionSpec n, Object argu);

   /**
    * f0 -> <SELECT_>
    * f1 -> [ <ALL_> | <DISTINCT_> | <UNIQUE_> ]
    * f2 -> SelectList(prn)
    * f3 -> [ IntoClause(prn) ]
    * f4 -> [ FromClause(prn) ]
    * f5 -> [ WhereClause(prn) ]
    * f6 -> [ GroupByClause(prn) ]
    * f7 -> [ HavingClause(prn) ]
    */
   public Object visit(SelectWithoutOrderAndSet n, Object argu);

   /**
    * f0 -> SelectTupleSpec(prn)
    * f1 -> ( "," SelectTupleSpec(prn) )*
    */
   public Object visit(SelectList n, Object argu);

   /**
    * f0 -> ( <STAR_> | TableName(prn) "." <STAR_> | SQLSimpleExpression(prn) [ SelectAliasSpec(prn) ] )
    */
   public Object visit(SelectTupleSpec n, Object argu);

   /**
    * f0 -> SQLMultiplicativeExpression(prn)
    * f1 -> ( SimpleExpressionOperand(prn) )*
    */
   public Object visit(SQLSimpleExpression n, Object argu);

   /**
    * f0 -> SQLPrimaryExpression(prn)
    * f1 -> ( SQLMultiplicativeExpressionOperand(prn) )*
    */
   public Object visit(SQLMultiplicativeExpression n, Object argu);

   /**
    * f0 -> ( <STAR_> | <DIVIDE_> | <MOD_> | <DIV_> | <MODULO_> | <AND_BITWISE_> | <OR_BITWISE_> | <XOR_BITWISE_> | <SHIFT_LEFT_BITWISE_> | <SHIFT_RIGHT_BITWISE_> | <CONTAINED_WITHIN_OR_EQUALS_> | <CONTAINS_OR_EQUALS_> )
    * f1 -> SQLPrimaryExpression(prn)
    */
   public Object visit(SQLMultiplicativeExpressionOperand n, Object argu);

   /**
    * f0 -> ( <PLUS_> | <MINUS_> | <CONCAT_> )
    * f1 -> SQLMultiplicativeExpression(prn)
    */
   public Object visit(SimpleExpressionOperand n, Object argu);

   /**
    * f0 -> [ <SQUARE_ROOT_> | <CUBE_ROOT_> | <FACTORIAL_PREFIX_> | <ABSOLUTE_> | <NOT_BITWISE_> ]
    * f1 -> [ <PLUS_> | <MINUS_> ]
    * f2 -> ( FunctionCall(prn) | TableColumn(prn) | PseudoColumn(prn) | numberValue(prn) | <PARENTHESIS_START_> SQLComplexExpression(prn) <PARENTHESIS_CLOSE_> | booleanLiteral(prn) | stringLiteral(prn) | NullLiterals(prn) | IntervalLiterals(prn) | TextLiterals(prn) | PreparedStmtParameter(prn) | TimeStampLiteral(prn) | TimeLiteral(prn) | DateLiteral(prn) | binaryLiteral(prn) | hex_decimalLiteral(prn) | IntegerLiteral(prn) | MacaddrLiteral(prn) | CidrLiteral(prn) | InetLiteral(prn) )
    * f3 -> [ <FACTORIAL_> ]
    * f4 -> [ "::" types() ]
    */
   public Object visit(SQLPrimaryExpression n, Object argu);

   /**
    * f0 -> <PARAM_PLACE_HOLDER>
    */
   public Object visit(PreparedStmtParameter n, Object argu);

   /**
    * f0 -> <TIMESTAMP_LITERAL>
    */
   public Object visit(TimeStampLiteral n, Object argu);

   /**
    * f0 -> <TIME_LITERAL>
    */
   public Object visit(TimeLiteral n, Object argu);

   /**
    * f0 -> <DATE_LITERAL>
    */
   public Object visit(DateLiteral n, Object argu);

   /**
    * f0 -> <INTERVAL_LITERAL>
    */
   public Object visit(IntervalLiterals n, Object argu);

   /**
    * f0 -> <TEXT_LITERAL>
    */
   public Object visit(TextLiterals n, Object argu);

   /**
    * f0 -> <NULL_>
    */
   public Object visit(NullLiterals n, Object argu);

   /**
    * f0 -> <TRUE_>
    *       | <FALSE_>
    */
   public Object visit(booleanLiteral n, Object argu);

   /**
    * f0 -> <BINARY_LITERAL>
    */
   public Object visit(binaryLiteral n, Object argu);

   /**
    * f0 -> <HEXDECIMAL_LITERAL>
    */
   public Object visit(hex_decimalLiteral n, Object argu);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public Object visit(IntegerLiteral n, Object argu);

   /**
    * f0 -> <MACADDR_LITERAL>
    */
   public Object visit(MacaddrLiteral n, Object argu);

   /**
    * f0 -> <CIDR_LITERAL>
    */
   public Object visit(CidrLiteral n, Object argu);

   /**
    * f0 -> <INET_LITERAL>
    */
   public Object visit(InetLiteral n, Object argu);

   /**
    * f0 -> <PARENTHESIS_START_>
    * f1 -> <SELECT_>
    * f2 -> [ <ALL_> | <DISTINCT_> ]
    * f3 -> SelectList(prn)
    * f4 -> FromClause(prn)
    * f5 -> [ WhereClause(prn) ]
    * f6 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(PseudoColumn n, Object argu);

   /**
    * f0 -> SQLArgument(prn)
    * f1 -> ( "," SQLArgument(prn) )*
    */
   public Object visit(SQLArgumentList n, Object argu);

   /**
    * f0 -> SQLSimpleExpression(prn)
    */
   public Object visit(SQLArgument n, Object argu);

   /**
    * f0 -> extendbObject(prn)
    */
   public Object visit(CharString n, Object argu);

   /**
    * f0 -> Func_Trunc(prn)
    *       | Func_Date(prn)
    *       | Func_Time(prn)
    *       | Func_TimeStamp(prn)
    *       | Func_CurrentDate(prn)
    *       | Func_PgCurrentDate(prn)
    *       | Func_CurrentTime(prn)
    *       | Func_PgCurrentTime(prn)
    *       | Func_PgCurrentTimeStamp(prn)
    *       | Func_Year(prn)
    *       | Func_Month(prn)
    *       | Func_Hour(prn)
    *       | Func_Minute(prn)
    *       | Func_Second(prn)
    *       | Func_AddDate(prn)
    *       | Func_AddTime(prn)
    *       | Func_DateDiff(prn)
    *       | Func_Day(prn)
    *       | Func_DayName(prn)
    *       | Func_DayOfMonth(prn)
    *       | Func_DayOfWeek(prn)
    *       | Func_DayOfYear(prn)
    *       | Func_MonthName(prn)
    *       | Func_SubDate(prn)
    *       | Func_SubTime(prn)
    *       | Func_WeekOfYear(prn)
    *       | Func_Now(prn)
    *       | Func_Abs(prn)
    *       | Func_Ceil(prn)
    *       | Func_Ceiling(prn)
    *       | Func_Exp(prn)
    *       | Func_Floor(prn)
    *       | Func_LN(prn)
    *       | Func_Log(prn)
    *       | Func_PI(prn)
    *       | Func_Power(prn)
    *       | Func_Round(prn)
    *       | Func_Sign(prn)
    *       | Func_TAsin(prn)
    *       | Func_TAtan(prn)
    *       | Func_TCos(prn)
    *       | Func_TCot(prn)
    *       | Func_TDegree(prn)
    *       | Func_Radians(prn)
    *       | Func_Sin(prn)
    *       | Func_Tan(prn)
    *       | Func_Avg(prn)
    *       | Func_Count(prn)
    *       | Func_Max(prn)
    *       | Func_Min(prn)
    *       | Func_Stdev(prn)
    *       | Func_Sum(prn)
    *       | Func_Variance(prn)
    *       | Func_Ascii(prn)
    *       | Func_Index(prn)
    *       | Func_Left(prn)
    *       | Func_Length(prn)
    *       | Func_Lower(prn)
    *       | Func_Lpad(prn)
    *       | Func_Rpad(prn)
    *       | Func_Ltrim(prn)
    *       | Func_Replace(prn)
    *       | Func_Right(prn)
    *       | Func_Rtrim(prn)
    *       | Func_SubStr(prn)
    *       | Func_Trim(prn)
    *       | Func_Upper(prn)
    *       | Func_Database(prn)
    *       | Func_Value(prn)
    *       | Func_Version(prn)
    *       | Func_Case(prn)
    *       | Func_TACos(prn)
    *       | Func_Log10(prn)
    *       | Func_Mod(prn)
    *       | Func_Sqrt(prn)
    *       | Func_Least(prn)
    *       | Func_TCosh(prn)
    *       | Func_Float(prn)
    *       | Func_Greatest(prn)
    *       | Func_TATan2(prn)
    *       | Func_TATn2(prn)
    *       | Func_SoundEx(prn)
    *       | Func_InitCap(prn)
    *       | Func_LFill(prn)
    *       | Func_MapChar(prn)
    *       | Func_NUM(prn)
    *       | Func_Concat(prn)
    *       | Func_User(prn)
    *       | Func_Cast(prn)
    *       | Func_TimeOfDay(prn)
    *       | Func_Custom(prn)
    *       | Func_IsFinite(prn)
    *       | Func_Extract(prn)
    *       | Func_DateTrunc(prn)
    *       | Func_DatePart(prn)
    *       | Func_Age(prn)
    *       | Func_LocalTime(prn)
    *       | Func_LocalTimeStamp(prn)
    *       | Func_BitLength(prn)
    *       | Func_CharLength(prn)
    *       | Func_Convert(prn)
    *       | Func_OctetLength(prn)
    *       | Func_Overlay(prn)
    *       | Func_Position(prn)
    *       | Func_Substring(prn)
    *       | Func_ToHex(prn)
    *       | Func_QuoteLiteral(prn)
    *       | Func_QuoteIdent(prn)
    *       | Func_Md5(prn)
    *       | Func_Chr(prn)
    *       | Func_PgClientEncoding(prn)
    *       | Func_Translate(prn)
    *       | Func_ToAscii(prn)
    *       | Func_StrPos(prn)
    *       | Func_SplitPart(prn)
    *       | Func_Repeat(prn)
    *       | Func_Encode(prn)
    *       | Func_Decode(prn)
    *       | Func_Btrim(prn)
    *       | Func_Width_bucket(prn)
    *       | Func_Setseed(prn)
    *       | Func_Random(prn)
    *       | Func_Cbrt(prn)
    *       | Func_GetBit(prn)
    *       | Func_GetByte(prn)
    *       | Func_ToDate(prn)
    *       | Func_ClockTimeStamp(prn)
    *       | Func_StatementTimeStamp(prn)
    *       | Func_TransactionTimeStamp(prn)
    *       | Func_NullIf(prn)
    *       | Func_SetBit(prn)
    *       | Func_SetByte(prn)
    *       | Func_ToChar(prn)
    *       | Func_ToNumber(prn)
    *       | Func_ToTimestamp(prn)
    *       | Func_AddMonths(prn)
    *       | Func_JustifyDays(prn)
    *       | Func_JustifyHours(prn)
    *       | Func_JustifyInterval(prn)
    *       | Func_LastDay(prn)
    *       | Func_MonthsBetween(prn)
    *       | Func_NextDay(prn)
    *       | Func_CurrentDatabase(prn)
    *       | Func_CurrentSchema(prn)
    *       | Func_SysDate(prn)
    *       | Func_BitAnd(prn)
    *       | Func_BitOr(prn)
    *       | Func_BoolAnd(prn)
    *       | Func_BoolOr(prn)
    *       | Func_CorrCov(prn)
    *       | Func_Regr(prn)
    *       | Func_RegexReplace(prn)
    *       | Func_Nvl(prn)
    *       | Func_Coalesce(prn)
    *       | Func_Abbrev(prn)
    *       | Func_Broadcast(prn)
    *       | Func_Family(prn)
    *       | Func_Host(prn)
    *       | Func_Hostmask(prn)
    *       | Func_Masklen(prn)
    *       | Func_Netmask(prn)
    *       | Func_Network(prn)
    *       | Func_Set_Masklen(prn)
    *       | Func_Text(prn)
    */
   public Object visit(FunctionCall n, Object argu);

   /**
    * f0 -> <CBRT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Cbrt n, Object argu);

   /**
    * f0 -> <GET_BIT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_GetBit n, Object argu);

   /**
    * f0 -> <GET_BYTE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_GetByte n, Object argu);

   /**
    * f0 -> <TO_DATE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," SQLArgument(prn) ]
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_ToDate n, Object argu);

   /**
    * f0 -> <CLOCK_TIMESTAMP_>
    * f1 -> [ <PARENTHESIS_START_> <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(Func_ClockTimeStamp n, Object argu);

   /**
    * f0 -> <STATEMENT_TIMESTAMP_>
    * f1 -> [ <PARENTHESIS_START_> <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(Func_StatementTimeStamp n, Object argu);

   /**
    * f0 -> <TRANSACTION_TIMESTAMP_>
    * f1 -> [ <PARENTHESIS_START_> <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(Func_TransactionTimeStamp n, Object argu);

   /**
    * f0 -> <NULLIF_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_NullIf n, Object argu);

   /**
    * f0 -> <SET_BIT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> ","
    * f6 -> SQLArgument(prn)
    * f7 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_SetBit n, Object argu);

   /**
    * f0 -> <SET_BYTE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> ","
    * f6 -> SQLArgument(prn)
    * f7 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_SetByte n, Object argu);

   /**
    * f0 -> <TO_CHAR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," SQLArgument(prn) ]
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_ToChar n, Object argu);

   /**
    * f0 -> <TO_NUMBER_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_ToNumber n, Object argu);

   /**
    * f0 -> <TO_TIMESTAMP_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_ToTimestamp n, Object argu);

   /**
    * f0 -> <ADD_MONTHS_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_AddMonths n, Object argu);

   /**
    * f0 -> <JUSTIFY_DAYS_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <INTERVAL_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_JustifyDays n, Object argu);

   /**
    * f0 -> <JUSTIFY_HOURS_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <INTERVAL_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_JustifyHours n, Object argu);

   /**
    * f0 -> <JUSTIFY_INTERVAL_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <INTERVAL_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_JustifyInterval n, Object argu);

   /**
    * f0 -> <LAST_DAY_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_LastDay n, Object argu);

   /**
    * f0 -> <MONTHS_BETWEEN_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_MonthsBetween n, Object argu);

   /**
    * f0 -> <NEXT_DAY_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_NextDay n, Object argu);

   /**
    * f0 -> <CURRENT_DATABASE_>
    * f1 -> [ <PARENTHESIS_START_> <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(Func_CurrentDatabase n, Object argu);

   /**
    * f0 -> <CURRENT_SCHEMA_>
    * f1 -> [ <PARENTHESIS_START_> <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(Func_CurrentSchema n, Object argu);

   /**
    * f0 -> <SYSDATE_>
    */
   public Object visit(Func_SysDate n, Object argu);

   /**
    * f0 -> <BIT_AND_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <DISTINCT_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_BitAnd n, Object argu);

   /**
    * f0 -> <BIT_OR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <DISTINCT_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_BitOr n, Object argu);

   /**
    * f0 -> ( <BOOL_AND_> | <EVERY_> )
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <DISTINCT_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_BoolAnd n, Object argu);

   /**
    * f0 -> <BOOL_OR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <DISTINCT_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_BoolOr n, Object argu);

   /**
    * f0 -> ( <CORR_> | <COVAR_POP_> | <COVAR_SAMP_> )
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_CorrCov n, Object argu);

   /**
    * f0 -> ( <REGR_AVGX_> | <REGR_AVGY_> | <REGR_COUNT_> | <REGR_INTERCEPT_> | <REGR_R2_> | <REGR_SLOPE_> | <REGR_SXX_> | <REGR_SXY_> | <REGR_SYY_> )
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Regr n, Object argu);

   /**
    * f0 -> <REGEXP_REPLACE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> ","
    * f6 -> SQLArgument(prn)
    * f7 -> [ "," SQLArgument(prn) ]
    * f8 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_RegexReplace n, Object argu);

   /**
    * f0 -> <NVL_> <PARENTHESIS_START_> SQLArgument(prn) "," SQLArgument(prn) <PARENTHESIS_CLOSE_>
    *       | <NVL2_> <PARENTHESIS_START_> SQLArgument(prn) "," SQLArgument(prn) "," SQLArgument(prn) <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Nvl n, Object argu);

   /**
    * f0 -> <COALESCE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgumentList(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Coalesce n, Object argu);

   /**
    * f0 -> <RANDOM_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Random n, Object argu);

   /**
    * f0 -> <SETSEED_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Setseed n, Object argu);

   /**
    * f0 -> <WIDTH_BUCKET_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> ","
    * f6 -> SQLArgument(prn)
    * f7 -> ","
    * f8 -> SQLArgument(prn)
    * f9 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Width_bucket n, Object argu);

   /**
    * f0 -> <BTRIM_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," SQLArgument(prn) ]
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Btrim n, Object argu);

   /**
    * f0 -> <DECODE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> ( "," SQLArgument(prn) )*
    * f6 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Decode n, Object argu);

   /**
    * f0 -> <ENCODE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Encode n, Object argu);

   /**
    * f0 -> <REPEAT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Repeat n, Object argu);

   /**
    * f0 -> <SPLIT_PART_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> ","
    * f6 -> SQLArgument(prn)
    * f7 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_SplitPart n, Object argu);

   /**
    * f0 -> <STRPOS_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_StrPos n, Object argu);

   /**
    * f0 -> <TO_ASCII_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," SQLArgument(prn) ]
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_ToAscii n, Object argu);

   /**
    * f0 -> <TRANSLATE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> ","
    * f6 -> SQLArgument(prn)
    * f7 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Translate n, Object argu);

   /**
    * f0 -> <PG_CLIENT_ENCODING_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_PgClientEncoding n, Object argu);

   /**
    * f0 -> <CHR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Chr n, Object argu);

   /**
    * f0 -> <MD5_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Md5 n, Object argu);

   /**
    * f0 -> <QUOTE_IDENT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_QuoteIdent n, Object argu);

   /**
    * f0 -> <QUOTE_LITERAL_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_QuoteLiteral n, Object argu);

   /**
    * f0 -> <TO_HEX_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_ToHex n, Object argu);

   /**
    * f0 -> <SUBSTRING_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ <FROM_> SQLArgument(prn) ]
    * f4 -> [ <FOR_> SQLArgument(prn) ]
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Substring n, Object argu);

   /**
    * f0 -> <POSITION_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <IN_>
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Position n, Object argu);

   /**
    * f0 -> <OVERLAY_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PLACING_>
    * f4 -> SQLArgument(prn)
    * f5 -> <FROM_>
    * f6 -> SQLArgument(prn)
    * f7 -> [ <FOR_> SQLArgument(prn) ]
    * f8 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Overlay n, Object argu);

   /**
    * f0 -> <OCTET_LENGTH_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_OctetLength n, Object argu);

   /**
    * f0 -> <CONVERT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ( <USING_> | "," )
    * f4 -> ( <STRING_LITERAL> | Identifier(prn) )
    * f5 -> [ "," ( <STRING_LITERAL> | Identifier(prn) ) ]
    * f6 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Convert n, Object argu);

   /**
    * f0 -> ( <CHAR_LENGTH_> | <CHARACTER_LENGTH_> )
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_CharLength n, Object argu);

   /**
    * f0 -> <BIT_LENGTH_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_BitLength n, Object argu);

   /**
    * f0 -> <LOCALTIME_>
    * f1 -> [ <PARENTHESIS_START_> SQLArgument(prn) <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(Func_LocalTime n, Object argu);

   /**
    * f0 -> <LOCALTIMESTAMP_>
    * f1 -> [ <PARENTHESIS_START_> SQLArgument(prn) <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(Func_LocalTimeStamp n, Object argu);

   /**
    * f0 -> <AGE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," SQLArgument(prn) ]
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Age n, Object argu);

   /**
    * f0 -> <DATEPART_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_DatePart n, Object argu);

   /**
    * f0 -> <DATETRUNC_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_DateTrunc n, Object argu);

   /**
    * f0 -> <EXTRACT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> ( <YEAR_FROM> | <QUARTER_FROM> | <MONTH_FROM> | <WEEK_FROM> | <DAY_FROM> | <HOUR_FROM> | <MINUTE_FROM> | <SECOND_FROM> | <DOY_FROM> | <DOW_FROM> | <DECADE_FROM> | <CENTURY_FROM> | <MILLISECOND_FROM> | <MILLENNIUM_FROM> | <MICROSECONDS_FROM> | <EPOCH_FROM> )
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Extract n, Object argu);

   /**
    * f0 -> <ISFINITE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_IsFinite n, Object argu);

   /**
    * f0 -> <TIMEOFDAY_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TimeOfDay n, Object argu);

   /**
    * f0 -> ( <USER_> | <CURRENT_USER_> )
    * f1 -> [ <PARENTHESIS_START_> <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(Func_User n, Object argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ SQLArgumentList(prn) ]
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Custom n, Object argu);

   /**
    * f0 -> <CONCAT_WORD>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Concat n, Object argu);

   /**
    * f0 -> <CASE_> SQLSimpleExpression(prn) ( <WHEN_> SQLSimpleExpression(prn) <THEN_> SQLSimpleExpression(prn) )* [ <ELSE_> SQLSimpleExpression(prn) ] <END_>
    *       | <CASE_> ( <WHEN_> SQLComplexExpression(prn) <THEN_> SQLSimpleExpression(prn) )* [ <ELSE_> SQLSimpleExpression(prn) ] <END_>
    */
   public Object visit(Func_Case n, Object argu);

   /**
    * f0 -> <ABS_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Abs n, Object argu);

   /**
    * f0 -> <CEIL_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Ceil n, Object argu);

   /**
    * f0 -> <CEILING_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Ceiling n, Object argu);

   /**
    * f0 -> <EXP_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Exp n, Object argu);

   /**
    * f0 -> <FLOOR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Floor n, Object argu);

   /**
    * f0 -> <LN_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_LN n, Object argu);

   /**
    * f0 -> <LOG_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," SQLArgument(prn) ]
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Log n, Object argu);

   /**
    * f0 -> <LOG10_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Log10 n, Object argu);

   /**
    * f0 -> <PI_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_PI n, Object argu);

   /**
    * f0 -> <POWER_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Power n, Object argu);

   /**
    * f0 -> <SIGN_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Sign n, Object argu);

   /**
    * f0 -> <ASIN_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TAsin n, Object argu);

   /**
    * f0 -> <ATAN2_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TATan2 n, Object argu);

   /**
    * f0 -> <ATN2_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TATn2 n, Object argu);

   /**
    * f0 -> <ATAN_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TAtan n, Object argu);

   /**
    * f0 -> <COS_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TCos n, Object argu);

   /**
    * f0 -> <COSH_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TCosh n, Object argu);

   /**
    * f0 -> <COT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TCot n, Object argu);

   /**
    * f0 -> <ACOS_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TACos n, Object argu);

   /**
    * f0 -> <DEGREE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TDegree n, Object argu);

   /**
    * f0 -> <RADIANS_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Radians n, Object argu);

   /**
    * f0 -> <SIN_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Sin n, Object argu);

   /**
    * f0 -> <TAN_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Tan n, Object argu);

   /**
    * f0 -> <ROUND_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," SQLArgument(prn) ]
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Round n, Object argu);

   /**
    * f0 -> ( <MOD_> | <MODULE_> )
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Mod n, Object argu);

   /**
    * f0 -> <FLOAT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Float n, Object argu);

   /**
    * f0 -> <GREATEST_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgumentList(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Greatest n, Object argu);

   /**
    * f0 -> <SQRT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Sqrt n, Object argu);

   /**
    * f0 -> <LEAST_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgumentList(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Least n, Object argu);

   /**
    * f0 -> <ASCII_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Ascii n, Object argu);

   /**
    * f0 -> ( <INDEX_> | <INSTR_> )
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> [ "," SQLArgument(prn) ]
    * f6 -> [ "," SQLArgument(prn) ]
    * f7 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Index n, Object argu);

   /**
    * f0 -> <LEFT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Left n, Object argu);

   /**
    * f0 -> <RIGHT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Right n, Object argu);

   /**
    * f0 -> <LENGTH_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Length n, Object argu);

   /**
    * f0 -> <LOWER_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Lower n, Object argu);

   /**
    * f0 -> <LPAD_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> [ "," SQLArgument(prn) ]
    * f6 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Lpad n, Object argu);

   /**
    * f0 -> <LTRIM_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," SQLArgument(prn) ]
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Ltrim n, Object argu);

   /**
    * f0 -> <REPLACE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> [ "," SQLArgument(prn) ]
    * f6 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Replace n, Object argu);

   /**
    * f0 -> <TRUNC_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," SQLArgument(prn) ]
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Trunc n, Object argu);

   /**
    * f0 -> <TRIM_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> ( <BOTH> | <LEADING> | <TRAILING> )
    * f3 -> [ SQLArgument(prn) ]
    * f4 -> <FROM_>
    * f5 -> SQLArgument(prn)
    * f6 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Trim n, Object argu);

   /**
    * f0 -> <RPAD_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> [ "," SQLArgument(prn) ]
    * f6 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Rpad n, Object argu);

   /**
    * f0 -> <RTRIM_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," SQLArgument(prn) ]
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Rtrim n, Object argu);

   /**
    * f0 -> <SUBSTR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> [ "," SQLArgument(prn) ]
    * f6 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_SubStr n, Object argu);

   /**
    * f0 -> <DATABASE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Database n, Object argu);

   /**
    * f0 -> <VERSION_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Version n, Object argu);

   /**
    * f0 -> <VALUE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> ( "," SQLArgument(prn) )*
    * f6 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Value n, Object argu);

   /**
    * f0 -> <AVERAGE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <DISTINCT_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Avg n, Object argu);

   /**
    * f0 -> <COUNT_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> ( <STAR_> | [ <DISTINCT_> | <ALL_> ] SQLArgument(prn) )
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Count n, Object argu);

   /**
    * f0 -> <MAX_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <DISTINCT_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Max n, Object argu);

   /**
    * f0 -> <MIN_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <DISTINCT_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Min n, Object argu);

   /**
    * f0 -> ( <STDDEV_> | <STDDEV_POP_> | <STDDEV_SAMP_> )
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <DISTINCT_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Stdev n, Object argu);

   /**
    * f0 -> ( <VARIANCE_> | <VARIANCE_POP_> | <VARIANCE_SAMP_> )
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <DISTINCT_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Variance n, Object argu);

   /**
    * f0 -> <SUM_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ <DISTINCT_> ]
    * f3 -> SQLArgument(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Sum n, Object argu);

   /**
    * f0 -> <UPPER_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Upper n, Object argu);

   /**
    * f0 -> <ABBREV_>
    * f1 -> "("
    * f2 -> SQLArgument(prn)
    * f3 -> ")"
    */
   public Object visit(Func_Abbrev n, Object argu);

   /**
    * f0 -> <BROADCAST_>
    * f1 -> "("
    * f2 -> SQLArgument(prn)
    * f3 -> ")"
    */
   public Object visit(Func_Broadcast n, Object argu);

   /**
    * f0 -> <FAMILY_>
    * f1 -> "("
    * f2 -> SQLArgument(prn)
    * f3 -> ")"
    */
   public Object visit(Func_Family n, Object argu);

   /**
    * f0 -> <HOST_>
    * f1 -> "("
    * f2 -> SQLArgument(prn)
    * f3 -> ")"
    */
   public Object visit(Func_Host n, Object argu);

   /**
    * f0 -> <HOSTMASK_>
    * f1 -> "("
    * f2 -> SQLArgument(prn)
    * f3 -> ")"
    */
   public Object visit(Func_Hostmask n, Object argu);

   /**
    * f0 -> <MASKLEN_>
    * f1 -> "("
    * f2 -> SQLArgument(prn)
    * f3 -> ")"
    */
   public Object visit(Func_Masklen n, Object argu);

   /**
    * f0 -> <NETMASK_>
    * f1 -> "("
    * f2 -> SQLArgument(prn)
    * f3 -> ")"
    */
   public Object visit(Func_Netmask n, Object argu);

   /**
    * f0 -> <NETWORK_>
    * f1 -> "("
    * f2 -> SQLArgument(prn)
    * f3 -> ")"
    */
   public Object visit(Func_Network n, Object argu);

   /**
    * f0 -> <SET_MASKLEN_>
    * f1 -> "("
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> ")"
    */
   public Object visit(Func_Set_Masklen n, Object argu);

   /**
    * f0 -> <TEXT_>
    * f1 -> "("
    * f2 -> SQLArgument(prn)
    * f3 -> ")"
    */
   public Object visit(Func_Text n, Object argu);

   /**
    * f0 -> <INT_LITERAL>
    */
   public Object visit(length n, Object argu);

   /**
    * f0 -> <INT_LITERAL>
    */
   public Object visit(position n, Object argu);

   /**
    * f0 -> extendbObject(prn)
    */
   public Object visit(TableColumn n, Object argu);

   /**
    * f0 -> ( TableName(prn) "." Identifier(prn) | Identifier(prn) )
    */
   public Object visit(extendbObject n, Object argu);

   /**
    * f0 -> [ <AS_> ]
    * f1 -> AliasName(prn)
    */
   public Object visit(SelectAliasSpec n, Object argu);

   /**
    * f0 -> Identifier(prn)
    */
   public Object visit(AliasName n, Object argu);

   /**
    * f0 -> SQLAndExpression(prn)
    * f1 -> ( SQLORExpression(prn) )*
    */
   public Object visit(SQLComplexExpression n, Object argu);

   /**
    * f0 -> SQLUnaryLogicalExpression(prn)
    * f1 -> [ <LEFTOUTER_> ]
    * f2 -> ( SQLAndExp(prn) )*
    */
   public Object visit(SQLAndExpression n, Object argu);

   /**
    * f0 -> <OR_>
    * f1 -> SQLAndExpression(prn)
    */
   public Object visit(SQLORExpression n, Object argu);

   /**
    * f0 -> <AND_>
    * f1 -> SQLUnaryLogicalExpression(prn)
    * f2 -> [ <LEFTOUTER_> ]
    */
   public Object visit(SQLAndExp n, Object argu);

   /**
    * f0 -> ( ExistsClause(prn) | [ <NOT_> ] SQLCondResult(prn) | [ <NOT_> ] SQLRelationalExpression(prn) )
    */
   public Object visit(SQLUnaryLogicalExpression n, Object argu);

   /**
    * f0 -> <TRUE_>
    *       | <FALSE_>
    */
   public Object visit(SQLCondResult n, Object argu);

   /**
    * f0 -> [ <NOT_> ]
    * f1 -> "EXISTS"
    * f2 -> <PARENTHESIS_START_>
    * f3 -> SubQuery(prn)
    * f4 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(ExistsClause n, Object argu);

   /**
    * f0 -> ( SQLExpressionList(prn) | SQLSimpleExpression(prn) )
    * f1 -> ( SQLRelationalOperatorExpression(prn) | ( SQLInClause(prn) | SQLBetweenClause(prn) | SQLLikeClause(prn) ) | IsNullClause(prn) | IsBooleanClause(prn) )?
    */
   public Object visit(SQLRelationalExpression n, Object argu);

   /**
    * f0 -> Relop(prn)
    * f1 -> ( [ "ALL" | "ANY" | "SOME" ] ( <PARENTHESIS_START_> SubQuery(prn) <PARENTHESIS_CLOSE_> | <PARENTHESIS_START_> SQLExpressionList(prn) <PARENTHESIS_CLOSE_> ) | SQLSimpleExpression(prn) )
    */
   public Object visit(SQLRelationalOperatorExpression n, Object argu);

   /**
    * f0 -> ( "=" | "!=" | "#" | "<>" | ">" | ">=" | "<" | "<=" )
    */
   public Object visit(Relop n, Object argu);

   /**
    * f0 -> [ <NOT_> ]
    * f1 -> <IN_>
    * f2 -> ( <PARENTHESIS_START_> SubQuery(prn) | <PARENTHESIS_START_> SQLExpressionList(prn) )
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(SQLInClause n, Object argu);

   /**
    * f0 -> [ <NOT_> ]
    * f1 -> <BETWEEN_>
    * f2 -> SQLSimpleExpression(prn)
    * f3 -> "AND"
    * f4 -> SQLSimpleExpression(prn)
    */
   public Object visit(SQLBetweenClause n, Object argu);

   /**
    * f0 -> ( [ <NOT_> ] ( <LIKE_> | <ILIKE_> | <SIMILAR_TO_> ) SQLSimpleExpression(prn) [ <ESCAPE_> SQLSimpleExpression(prn) ] | ( <NOT_BITWISE_> | <REGEX_NOT_MATCHES_> | <REGEX_MATCHES_CASE_INSTV_> | <REGEX_NOT_MATCHES_CASE_INSTV_> | <OVERLAPS_> ) SQLSimpleExpression(prn) )
    */
   public Object visit(SQLLikeClause n, Object argu);

   /**
    * f0 -> SelectWithoutOrder(prn)
    */
   public Object visit(SubQuery n, Object argu);

   /**
    * f0 -> ( "IS" [ <NOT_> ] | "=" | "!=" )
    * f1 -> "NULL"
    */
   public Object visit(IsNullClause n, Object argu);

   /**
    * f0 -> ( "IS" [ <NOT_> ] | "=" | "!=" )
    * f1 -> ( "TRUE" | "FALSE" )
    */
   public Object visit(IsBooleanClause n, Object argu);

   /**
    * f0 -> <INTO_>
    * f1 -> [ <TEMPORARY_> | <TEMP_> ]
    * f2 -> [ <TABLE_> ]
    * f3 -> TableName(prn)
    */
   public Object visit(IntoClause n, Object argu);

   /**
    * f0 -> <FROM_>
    * f1 -> TableList(prn)
    */
   public Object visit(FromClause n, Object argu);

   /**
    * f0 -> TableName(prn) [ SelectAliasSpec(prn) ]
    *       | <PARENTHESIS_START_> SelectWithoutOrder(prn) <PARENTHESIS_CLOSE_> [ SelectAliasSpec(prn) ] [ <PARENTHESIS_START_> ColumnNameList(prn) <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(TableSpec n, Object argu);

   /**
    * f0 -> FromTableSpec(prn)
    * f1 -> ( "," FromTableSpec(prn) )*
    */
   public Object visit(TableList n, Object argu);

   /**
    * f0 -> TableSpec(prn)
    * f1 -> ( <CROSS_> <JOIN_> TableSpec(prn) | ( [ <INNER_> ] <JOIN_> TableSpec(prn) JoinSpec(prn) | ( <LEFT_> | <RIGHT_> | <FULL_> ) [ <OUTER_> ] <JOIN_> TableSpec(prn) JoinSpec(prn) ) | <NATURAL_> ( [ <INNER_> ] <JOIN_> TableSpec(prn) | ( <LEFT_> | <RIGHT_> | <FULL_> ) [ <OUTER_> ] <JOIN_> TableSpec(prn) ) )*
    */
   public Object visit(FromTableSpec n, Object argu);

   /**
    * f0 -> "ON" SQLComplexExpression(prn)
    *       | <USING_> <PARENTHESIS_START_> ColumnNameList(prn) <PARENTHESIS_CLOSE_>
    */
   public Object visit(JoinSpec n, Object argu);

   /**
    * f0 -> <WHERE_>
    * f1 -> SQLComplexExpression(prn)
    */
   public Object visit(WhereClause n, Object argu);

   /**
    * f0 -> <GROUP_BY_>
    * f1 -> SQLExpressionList(prn)
    */
   public Object visit(GroupByClause n, Object argu);

   /**
    * f0 -> SQLExpressionListItem(prn)
    * f1 -> ( "," SQLExpressionListItem(prn) )*
    */
   public Object visit(SQLExpressionList n, Object argu);

   /**
    * f0 -> SQLSimpleExpression(prn)
    */
   public Object visit(SQLExpressionListItem n, Object argu);

   /**
    * f0 -> "HAVING"
    * f1 -> SQLComplexExpression(prn)
    */
   public Object visit(HavingClause n, Object argu);

   /**
    * f0 -> <ORDER_BY_>
    * f1 -> OrderByItem(prn)
    * f2 -> ( "," OrderByItem(prn) )*
    */
   public Object visit(OrderByClause n, Object argu);

   /**
    * f0 -> <LIMIT_>
    * f1 -> ( <INT_LITERAL> | <ALL_> )
    */
   public Object visit(LimitClause n, Object argu);

   /**
    * f0 -> <OFFSET_>
    * f1 -> <INT_LITERAL>
    */
   public Object visit(OffsetClause n, Object argu);

   /**
    * f0 -> SQLSimpleExpression(prn)
    * f1 -> [ "ASC" | "DESC" ]
    */
   public Object visit(OrderByItem n, Object argu);

   /**
    * f0 -> <ADDDATE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_AddDate n, Object argu);

   /**
    * f0 -> <ADDTIME_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_AddTime n, Object argu);

   /**
    * f0 -> <DATE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Date n, Object argu);

   /**
    * f0 -> <DATEDIFF_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_DateDiff n, Object argu);

   /**
    * f0 -> <DAY_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Day n, Object argu);

   /**
    * f0 -> <DAYNAME_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_DayName n, Object argu);

   /**
    * f0 -> <DAYOFMONTH_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_DayOfMonth n, Object argu);

   /**
    * f0 -> <DAYOFWEEK_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_DayOfWeek n, Object argu);

   /**
    * f0 -> <DAYOFYEAR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_DayOfYear n, Object argu);

   /**
    * f0 -> <MONTHNAME_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_MonthName n, Object argu);

   /**
    * f0 -> <SUBDATE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_SubDate n, Object argu);

   /**
    * f0 -> "SUBTIME"
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_SubTime n, Object argu);

   /**
    * f0 -> <TIME_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Time n, Object argu);

   /**
    * f0 -> ( <CURDATE_> | <DATE_> )
    * f1 -> <PARENTHESIS_START_>
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_CurrentDate n, Object argu);

   /**
    * f0 -> <CURRENTDATE_>
    */
   public Object visit(Func_PgCurrentDate n, Object argu);

   /**
    * f0 -> <CURRENT_TIME_>
    * f1 -> [ <PARENTHESIS_START_> SQLArgument(prn) <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(Func_PgCurrentTime n, Object argu);

   /**
    * f0 -> ( <CURTIME_> | <TIME_> )
    * f1 -> <PARENTHESIS_START_>
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_CurrentTime n, Object argu);

   /**
    * f0 -> <CURRENT_TIMESTAMP_>
    * f1 -> [ <PARENTHESIS_START_> SQLArgument(prn) <PARENTHESIS_CLOSE_> ]
    */
   public Object visit(Func_PgCurrentTimeStamp n, Object argu);

   /**
    * f0 -> <YEAR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Year n, Object argu);

   /**
    * f0 -> <MONTH_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Month n, Object argu);

   /**
    * f0 -> <MINUTE_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Minute n, Object argu);

   /**
    * f0 -> <HOUR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Hour n, Object argu);

   /**
    * f0 -> <SECOND_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Second n, Object argu);

   /**
    * f0 -> <TIMESTAMP_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> [ SQLArgument(prn) ]
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_TimeStamp n, Object argu);

   /**
    * f0 -> <WEEKOFYEAR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_WeekOfYear n, Object argu);

   /**
    * f0 -> <NOW_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Now n, Object argu);

   /**
    * f0 -> <SOUNDEX_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_SoundEx n, Object argu);

   /**
    * f0 -> <INITCAP_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_InitCap n, Object argu);

   /**
    * f0 -> <LFILL_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> ","
    * f4 -> SQLArgument(prn)
    * f5 -> [ "," SQLArgument(prn) ]
    * f6 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_LFill n, Object argu);

   /**
    * f0 -> <MAPCHAR_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> [ "," <INT_LITERAL> ]
    * f4 -> [ "," Identifier(prn) ]
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_MapChar n, Object argu);

   /**
    * f0 -> <NUM_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_NUM n, Object argu);

   /**
    * f0 -> <CAST_>
    * f1 -> <PARENTHESIS_START_>
    * f2 -> SQLArgument(prn)
    * f3 -> <AS_>
    * f4 -> ( types() | <NULL_> )
    * f5 -> <PARENTHESIS_CLOSE_>
    */
   public Object visit(Func_Cast n, Object argu);

   /**
    * f0 -> Identifier(prn)
    * f1 -> ( "," Identifier(prn) )*
    */
   public Object visit(ColumnNameList n, Object argu);

   /**
    * f0 -> ( Identifier(prn) | <TEMPDOT_> Identifier(prn) | <PUBLICDOT_> Identifier(prn) | <QPUBLICDOT_> Identifier(prn) )
    */
   public Object visit(TableName n, Object argu);

   /**
    * f0 -> <DECIMAL_LITERAL>
    *       | <INT_LITERAL>
    *       | <SCIENTIFIC_LITERAL>
    */
   public Object visit(FloatingPointNumber n, Object argu);

   /**
    * f0 -> <SHOW_DATABASES_>
    */
   public Object visit(ShowDatabases n, Object argu);

   /**
    * f0 -> <SHOW_AGENTS_>
    */
   public Object visit(ShowAgents n, Object argu);

   /**
    * f0 -> <SHOW_STATEMENTS_>
    */
   public Object visit(ShowStatements n, Object argu);

   /**
    * f0 -> <SHOW_TABLES_>
    */
   public Object visit(ShowTables n, Object argu);

   /**
    * f0 -> <SHOW_TRAN_ISOLATION_>
    */
   public Object visit(ShowTranIsolation n, Object argu);

   /**
    * f0 -> <BEGIN_>
    * f1 -> [ ( <TRANSACTION_> | <TRAN_> | <WORK_> ) ]
    */
   public Object visit(BeginTransaction n, Object argu);

   /**
    * f0 -> ( <COMMIT_> | <END_> )
    * f1 -> [ ( <TRANSACTION_> | <TRAN_> | <WORK_> ) ]
    */
   public Object visit(CommitTransaction n, Object argu);

   /**
    * f0 -> <ROLLBACK_>
    * f1 -> [ ( <TRANSACTION_> | <TRAN_> | <WORK_> ) ]
    */
   public Object visit(RollbackTransaction n, Object argu);

   /**
    * f0 -> ( <DESCRIBE_> | <SHOW_TABLE_> | <SHOW_VIEW_> )
    * f1 -> TableName(prn)
    */
   public Object visit(DescribeTable n, Object argu);

   /**
    * f0 -> <SHOW_CONSTRAINTS_>
    * f1 -> <ON_>
    * f2 -> TableName(prn)
    */
   public Object visit(ShowConstraints n, Object argu);

   /**
    * f0 -> <SHOW_INDEXES_>
    * f1 -> <ON_>
    * f2 -> TableName(prn)
    */
   public Object visit(ShowIndexes n, Object argu);

   /**
    * f0 -> <SHOW_USERS_>
    */
   public Object visit(ShowUsers n, Object argu);

   /**
    * f0 -> <SHOW_VIEWS_>
    */
   public Object visit(ShowViews n, Object argu);

   /**
    * f0 -> <DEALLOCATE_>
    * f1 -> [ <PREPARE_> ]
    * f2 -> Identifier(prn)
    */
   public Object visit(Deallocate n, Object argu);

   /**
    * f0 -> <CREATE_>
    * f1 -> <USER_>
    * f2 -> Identifier(prn)
    * f3 -> <PASSWORD_>
    * f4 -> Identifier(prn)
    * f5 -> [ <DBA_> | <RESOURCE_> | <STANDARD_> ]
    */
   public Object visit(CreateUser n, Object argu);

   /**
    * f0 -> <DROP_>
    * f1 -> <USER_>
    * f2 -> Identifier(prn)
    */
   public Object visit(DropUser n, Object argu);

   /**
    * f0 -> <ALTER_>
    * f1 -> <USER_>
    * f2 -> Identifier(prn)
    * f3 -> [ <PASSWORD_> Identifier(prn) ]
    * f4 -> [ <DBA_> | <RESOURCE_> | <STANDARD_> ]
    */
   public Object visit(AlterUser n, Object argu);

   /**
    * f0 -> <PUBLIC_>
    *       | Identifier(prn)
    */
   public Object visit(Grantee n, Object argu);

   /**
    * f0 -> Grantee(prn)
    * f1 -> ( "," Grantee(prn) )*
    */
   public Object visit(GranteeList n, Object argu);

   /**
    * f0 -> <STAR_>
    *       | Identifier(prn) ( "," Identifier(prn) )*
    */
   public Object visit(TableListForGrant n, Object argu);

   /**
    * f0 -> <SELECT_>
    *       | <INSERT_>
    *       | <UPDATE_>
    *       | <DELETE_>
    *       | <REFERENCES_>
    *       | <INDEX_>
    *       | <ALTER_>
    */
   public Object visit(Privilege n, Object argu);

   /**
    * f0 -> <ALL_>
    *       | Privilege(prn) ( "," Privilege(prn) )*
    */
   public Object visit(PrivilegeList n, Object argu);

   /**
    * f0 -> <GRANT_>
    * f1 -> PrivilegeList(prn)
    * f2 -> <ON_>
    * f3 -> [ <TABLE_> ]
    * f4 -> TableListForGrant(prn)
    * f5 -> <TO_>
    * f6 -> GranteeList(prn)
    */
   public Object visit(Grant n, Object argu);

   /**
    * f0 -> <REVOKE_>
    * f1 -> PrivilegeList(prn)
    * f2 -> <ON_>
    * f3 -> [ <TABLE_> ]
    * f4 -> TableListForGrant(prn)
    * f5 -> <FROM_>
    * f6 -> GranteeList(prn)
    */
   public Object visit(Revoke n, Object argu);

   /**
    * f0 -> <CLUSTER_>
    * f1 -> [ Identifier(prn) [ <ON_> Identifier(prn) ] ]
    */
   public Object visit(Cluster n, Object argu);

   /**
    * f0 -> <TRUNCATE_>
    * f1 -> [ <TABLE_> ]
    * f2 -> TableName(prn)
    */
   public Object visit(Truncate n, Object argu);

   /**
    * f0 -> <KILL_>
    * f1 -> <INT_LITERAL>
    */
   public Object visit(Kill n, Object argu);

   /**
    * f0 -> <UNLISTEN_>
    * f1 -> [ Identifier(prn) | <STAR_> ]
    */
   public Object visit(Unlisten n, Object argu);

}
