//
// Generated by JTB 1.2.2
//

package com.edb.gridsql.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <NVL_> <PARENTHESIS_START_> SQLArgument(prn) "," SQLArgument(prn) <PARENTHESIS_CLOSE_>
 *       | <NVL2_> <PARENTHESIS_START_> SQLArgument(prn) "," SQLArgument(prn) "," SQLArgument(prn) <PARENTHESIS_CLOSE_>
 */
public class Func_Nvl implements Node {
   public NodeChoice f0;

   public Func_Nvl(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(com.edb.gridsql.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(com.edb.gridsql.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

