//
// Generated by JTB 1.2.2
//

package com.edb.gridsql.parser.core.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(com.edb.gridsql.parser.core.visitor.Visitor v);
   public Object accept(com.edb.gridsql.parser.core.visitor.ObjectVisitor v, Object argu);

}

