//
// Generated by JTB 1.2.2
//

package com.edb.gridsql.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> IntegerDataType()
 *       | SmallIntDataType()
 *       | RealDataType()
 *       | DoublePrecision()
 *       | FloatDataType()
 *       | DecimalDataType()
 *       | NumericDataType()
 *       | FixedDataType()
 *       | CharachterDataType()
 *       | VarCharDataType()
 *       | DateDataType()
 *       | TimeDataType()
 *       | TimeStampDataType()
 *       | BooleanDataType()
 *       | NationalCharDataType()
 *       | SerialDataType()
 *       | BigSerialDataType()
 *       | BigIntDataType()
 *       | IntervalDataType()
 *       | TextDataType()
 *       | BLOBDataType()
 *       | BitDataType()
 *       | VarBitDataType()
 *       | MacAddrDataType()
 *       | CidrDataType()
 *       | InetDataType()
 */
public class types implements Node {
   public NodeChoice f0;

   public types(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(com.edb.gridsql.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(com.edb.gridsql.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

